language: python
sudo: required
python:
  - "2.7"

env:
  global:
    - secure: "a2BFGdnevqXExNYKIOc8+5nlF5Vr9RETOrOXncAu6T5c6zMvfXte636ldqfe3VpCmz5EvI5brvXreI4Bktifs2D5TP6fdVCGpB/QGoN8BYTKV6+uQhCuVighFIpBQgvJd6lwhrdbh72FCDbHr6b/l0Emncf0Q3zBWLvrfBi7pWOR+T7w4qGaL9Jk6ysSy81g7TFi499vsPPZzOrgRYyx4whwRyAt/uj0u681J4wgXidaukfWYVY3+dqmcVz25eWhrfO0KaIEALbwCzLHVDGRDK+Y0DdJsWjBBLAOeNUYcc7B+DHbGWA2Wf3+Ya2CaSL7aBf9CVXlNNXYNnEtTcD4BHi/F8gV6W4n79tjjO+Takl5XrW086JN7UPdVZJTT3XEh4bsawA0cIMbp1FO5KdPerYxO+JBKReArmGYfbtuGTFPgwqKoq5Eg8ZjlSTcIhi25uT5Ce5Rk5KFd+8TIancvzPZuynRFe8NgrwmtblnoGPs6SAJOged5O6OsI7SHZQ3VW9GTll/xRkm96A1SxNn+q9IIHeHNirZfce0cYnfnnSXGBtujqT/r1hxUOJqHq/AthoJydFlsi3gCnp8T8NjnADwl4HAAaN/iAZSiHxTZvePOp7qLgzEncSgIrfj3YmNQT+kq2aDQrslTeqCQic5ZfqN8/fFUgNtSfsm2Kl+8/A="
    - secure: "D1GuHrsNJGnHO+Xjx/aHSVzZpcUS1Zjzc8fTlE6bYTihQrTUuUA7Pidg6KbdTDbKs0URiDJPELsK9UQJEUh8Bv0hlO5rm/af8K0ymPRzrdkIAteES1w3dFeLjHGYm6YQBpPzL71HvlYqiQIU5MjSPeQcGCbM2XrOsNvJPTMCMs1y5dgn0/oNNaNn3jVDa5HQAiXFj/RMSgPMDurpX72LgYLN21GRHo0/s/VKDywhLU5e2TX1PpLimmFJUdieG8blTIPsOhrsRQaj5S8Dw8n6o0d8/1lG9y/OUWFrjQbaesmWHglhnWMDjZ0kXR3bP7jIiB785ESBd+XlPZXnepq6h5fTv+UrcawsiDH61e/5pUGmKFnboUQ3XcLbfqpODjb6IlgQkQxVTI0H9uIJ1Yo7Tyu7ay1lUO+QXVCPNm1wieoyp5mXnJp5yR9mZJ8T8g65sHMGCeQB0Q1WCuAKNKoFlikm4cLrZddOVwcH5jTiA7iRuSYyGqc5pOjuAhLDWR04/7IRRGESCBa+8YxLPQykUuseCuF/39b0nDgMCvrpkcafoLTCXc/abNf5p38c6WoL+sXXlzr71NKrF09WdSo8WJ7/XsneHbmGE0pLdPiDyHsLO4gkm9u0srdX7ffQyjcR3FWCmf4okR7JpxcqnTXI6d+GcG7zDMpbkoHyevPvZY0="
    - AWS_DEFAULT_REGION=us-east-1
    - ARN=arn:aws:lambda:us-east-1:738332650714:function:getRandomQuote

addons:
  apt:
    packages:
    - zip

install:
  - pip install awscli

script:
  - cd ~/build/frankgreco/alexa/src && zip -r randomQuote.zip *
  - cd ~/build/frankgreco/alexa/src && aws lambda update-function-code --function-name $ARN --zip-file fileb://randomQuote.zip --publish
