sudo: required
language: node_js
node_js:
  - "4.3"

env:
  global:
    - secure: "a2BFGdnevqXExNYKIOc8+5nlF5Vr9RETOrOXncAu6T5c6zMvfXte636ldqfe3VpCmz5EvI5brvXreI4Bktifs2D5TP6fdVCGpB/QGoN8BYTKV6+uQhCuVighFIpBQgvJd6lwhrdbh72FCDbHr6b/l0Emncf0Q3zBWLvrfBi7pWOR+T7w4qGaL9Jk6ysSy81g7TFi499vsPPZzOrgRYyx4whwRyAt/uj0u681J4wgXidaukfWYVY3+dqmcVz25eWhrfO0KaIEALbwCzLHVDGRDK+Y0DdJsWjBBLAOeNUYcc7B+DHbGWA2Wf3+Ya2CaSL7aBf9CVXlNNXYNnEtTcD4BHi/F8gV6W4n79tjjO+Takl5XrW086JN7UPdVZJTT3XEh4bsawA0cIMbp1FO5KdPerYxO+JBKReArmGYfbtuGTFPgwqKoq5Eg8ZjlSTcIhi25uT5Ce5Rk5KFd+8TIancvzPZuynRFe8NgrwmtblnoGPs6SAJOged5O6OsI7SHZQ3VW9GTll/xRkm96A1SxNn+q9IIHeHNirZfce0cYnfnnSXGBtujqT/r1hxUOJqHq/AthoJydFlsi3gCnp8T8NjnADwl4HAAaN/iAZSiHxTZvePOp7qLgzEncSgIrfj3YmNQT+kq2aDQrslTeqCQic5ZfqN8/fFUgNtSfsm2Kl+8/A="
    - secure: "D1GuHrsNJGnHO+Xjx/aHSVzZpcUS1Zjzc8fTlE6bYTihQrTUuUA7Pidg6KbdTDbKs0URiDJPELsK9UQJEUh8Bv0hlO5rm/af8K0ymPRzrdkIAteES1w3dFeLjHGYm6YQBpPzL71HvlYqiQIU5MjSPeQcGCbM2XrOsNvJPTMCMs1y5dgn0/oNNaNn3jVDa5HQAiXFj/RMSgPMDurpX72LgYLN21GRHo0/s/VKDywhLU5e2TX1PpLimmFJUdieG8blTIPsOhrsRQaj5S8Dw8n6o0d8/1lG9y/OUWFrjQbaesmWHglhnWMDjZ0kXR3bP7jIiB785ESBd+XlPZXnepq6h5fTv+UrcawsiDH61e/5pUGmKFnboUQ3XcLbfqpODjb6IlgQkQxVTI0H9uIJ1Yo7Tyu7ay1lUO+QXVCPNm1wieoyp5mXnJp5yR9mZJ8T8g65sHMGCeQB0Q1WCuAKNKoFlikm4cLrZddOVwcH5jTiA7iRuSYyGqc5pOjuAhLDWR04/7IRRGESCBa+8YxLPQykUuseCuF/39b0nDgMCvrpkcafoLTCXc/abNf5p38c6WoL+sXXlzr71NKrF09WdSo8WJ7/XsneHbmGE0pLdPiDyHsLO4gkm9u0srdX7ffQyjcR3FWCmf4okR7JpxcqnTXI6d+GcG7zDMpbkoHyevPvZY0="
    - secure: "CL+8iaizZe4GPIPKxPNyPR2WfckwZwxUueT/ivNWruE+xUjpPoiO06WBcE1koUzufbHMgE3GiPsj8t9/3MMmCgn27XKpLovNEFyscb8nu5VG0KvMSPNmbEkulmDXHm5ObGALJ2K+QLTMos0XCMlSGXlkll8EFcxFtXMxwgsbruR+Q2ZufQMzV5Cdz2/VzUNfP0gYlb2Mv4ga2rMSLbLETqRVjgQFARDLsCBMLQbitlX52gQBkJavuTh8vLxdFpRy75HzsmWz2p55kQFa15Sh1fjdo7VIUBYCG9RhhM+xe3ugEVqCDjjZD6oFmYbcYJf+j/BI4BKTxXCeD95JetQijsHhbZn+/nTdX+Ra6RLSJBgUmd11mDUmXIYczJ5px8XgQ6EiTUKdY3TpAtoBmqhr4F2kAEB3RYecMWPbtQ/jrPowpZb3tMxjR96IDbQTRehmIqqav3Q+oquRGQWSz+bP4YINbMCp4+wpAvlHfCTdtKI7AA1eB0yzc9lqXRe2pMlN1wT7YEzOdrMCeJwYHo7CCxZC/41wiB7yyfLWpvJxJf3yRRcAB+E4yKgF6RQsEY+d2F3nPl5BXJHA6R3Gn595r9css1g74TF8dAB/F2Leiv+uyLVcazpTXHyrt3SnYB1Qjs8pPhoYQBgDa9gNrRisyBrt02qDRAaiweuqXCA8W0Q="
    - AWS_DEFAULT_REGION=us-east-1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - zip
      - jq
      - unzip


install:
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - ./awscli-bundle/install -b ~/bin/aws

script:
  - cd ~/build/frankgreco/alexa && chmod +x deploy.sh && ./deploy.sh
